// Generated by GPT-5

#include <bits/stdc++.h>
typedef int64_t LL;
using std::cin, std::cout, std::endl, std::vector;

const LL NEG_INF = (LL)-4e18;

LL best;

// dfs 逐个食材决定：0=不用，1=给 x，2=给 y
void dfs(int i, const vector<LL>& a, LL x, LL y, int cntx, int cnty, LL sumx, LL sumy) {
    if (i == (int)a.size()) {
        if (cntx == cnty) {                     // 只能在天数匹配时更新答案
            best = std::max(best, x * sumx + y * sumy);
        }
        return;
    }

    // 0. 不用第 i 个
    dfs(i + 1, a, x, y, cntx, cnty, sumx, sumy);

    // 1. 第 i 个给食谱 x
    dfs(i + 1, a, x, y, cntx + 1, cnty, sumx + a[i], sumy);

    // 2. 第 i 个给食谱 y
    dfs(i + 1, a, x, y, cntx, cnty + 1, sumx, sumy + a[i]);
}

void solve() {
    int n;
    LL x, y;
    cin >> n >> x >> y;
    vector<LL> a(n);
    for (auto &v : a) cin >> v;

    best = 0;                                   // 做 0 天饭也是合法的
    dfs(0, a, x, y, 0, 0, 0, 0);
    cout << best << endl;
}

int main() {
    std::ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int T = 1;
    cin >> T;
    while (T--) solve();
    return 0;
}